// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlQX4qjIsHZIG5hC5kLu-5MeXWNwtWn0I',
    appId: '1:924815235531:web:3cacd239d3413a6892fe4e',
    messagingSenderId: '924815235531',
    projectId: 'dementia-a6cde',
    authDomain: 'dementia-a6cde.firebaseapp.com',
    storageBucket: 'dementia-a6cde.appspot.com',
    measurementId: 'G-HZ37S6KM8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXqAhJKgog0z-zLRWUzOb_9jwmBFSqJLI',
    appId: '1:924815235531:android:08bb87e957381aaa92fe4e',
    messagingSenderId: '924815235531',
    projectId: 'dementia-a6cde',
    storageBucket: 'dementia-a6cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhxFJK5_Dfw9HrL7El5SgvePTUitR9rjs',
    appId: '1:924815235531:ios:845fb948d1395e6a92fe4e',
    messagingSenderId: '924815235531',
    projectId: 'dementia-a6cde',
    storageBucket: 'dementia-a6cde.appspot.com',
    iosBundleId: 'com.example.dementia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhxFJK5_Dfw9HrL7El5SgvePTUitR9rjs',
    appId: '1:924815235531:ios:845fb948d1395e6a92fe4e',
    messagingSenderId: '924815235531',
    projectId: 'dementia-a6cde',
    storageBucket: 'dementia-a6cde.appspot.com',
    iosBundleId: 'com.example.dementia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlQX4qjIsHZIG5hC5kLu-5MeXWNwtWn0I',
    appId: '1:924815235531:web:914c0a057cbedf4392fe4e',
    messagingSenderId: '924815235531',
    projectId: 'dementia-a6cde',
    authDomain: 'dementia-a6cde.firebaseapp.com',
    storageBucket: 'dementia-a6cde.appspot.com',
    measurementId: 'G-L2M38K9Z5W',
  );

}